### ISSUE TITLE
Unexpected type signature for `andThen`

### ISSUE THREAD

**Issue by knuton** [stoeffel/elm-verify#12]
Is the unusual type signature of `andThen` intentional? My expectation was that it would behave analogously to `Maybe.andThen`, `Result.andThen` etc.

The definition I expected is this:

```elm
andThen : (a -> Validator err input b) -> Validator err input a -> Validator err input b
andThen callback validator input =
    validator input |> Result.andThen (\a -> callback a <| input)
```

This is useful when the kind of verification to be performed depends on the result of a previous verification.

Your current definition does not allow that but requires for the second verification to be picked statically. I can see how it might be called "andThen", but I always assumed this name to be conventionally reserved for functions of type `(a -> t b) -> t a -> t b`, where in this case `t = Validator err input`.

Maybe "compose" could be a good name to use instead? Or, less formally: "pipe", "next", "andAlso"

**Comment by stoeffel** [comment]
Yes, I think we should rename the current `andThen` to `pipe` and create an `andThen` like you proposed.
If someone wants to add that it would be highly appreciated.

**Comment by gyzerok** [comment]
In our project we happened to hit the same problem. In our specific case it was also about having custom validator.

Let's assume that current `andThen` could be renamed to `pipe`. Then let's compare how our example will look in case of changing name and in case of changing signature.

```elm
String.Verify.notBlank "..."
  |> Verify.pipe
    (Verify.ok identity
      |> Verify.custom
        (\str ->
          if isInvalid str then
            Err [".."]
          else
            Ok str
        )
    )
```

```elm
String.Verify.notBlank "..."
  |> Verify.andThen
    (\str ->
      if isInvalid str then 
        Verify.fail ".."
      else
        Verify.ok str
    )
```

I would propose to change signature of `andThen` rather then name because:
1. It will work better with custom validations. I would imagine that they are quite common in prod codebases.
2. Developer who is using this library can use same intuition built form using other packages from Elm ecosystem
3. This way is closer to how decoders work. And if I understand it correctly, this library want to use "similar" idea.

**Comment by stoeffel** [comment]
Oh, sorry my proposal was actually to have both.
So having
```elm
compose
    :  Validator error result finally
    -> Validator error input result
    -> Validator error input finally

-- and
andThen : (a -> Validator err input b) -> Validator err input a -> Validator err input b
```
