### ISSUE TITLE
Consider creating Verify.map

### ISSUE THREAD

**Issue by michaeljones** [stoeffel/elm-verify#6]
To perform the same function as `Json.Decode.map`

I'm not great at this stuff but I have:

```elm
map : (a -> b) -> V.Validator error input a -> V.Validator error input b
map func validator =
    validator >> Result.map func
```

**Comment by stoeffel** [comment]
I think since this is just `Result.map`  I don't want to add it, but maybe adding some docs would be good. I think we should avoid mirroring Result's api and just use that directly

**Comment by michaeljones** [comment]
Thanks for the response. As far as I can tell, it isn't quite `Result.map` as Validator isn't quite a Result type (being `input -> Result`) which I think means that you need to define this for a smooth experience.

I'm a bit torn. I kind of like the idea of hiding the fact that it is a Result type by providing all the necessary API but I guess it is a given that at the end of the Verify process, you're going to have deal with the Result type that tells you if it has been successful and it is good to see the Result at that point.

**Comment by stoeffel** [comment]
We’ve used this library internally at noredink for some time with the
implementation of Validator hidden and it was painful. I think it makes
sense to do transformation on the result after the validator was called,
but you can always just compose a Result.map with your Validator.
`myValidator >> Result.map someFancyTransformation`. As you said at some
point you have to deal with the result anyways and I like this because it
also allows to compose with Result.mapError which we often do to add some
extra info to the error. Obviously you could add a mapError to this lib as
well, but we would just mirror more of what Result already has.
